version: '3.9'

services:
  api:
    image: api-project:v1
    build:
      context: backend
    ports:
      - 5000:5000
    networks:
      - web-net

  frontend:
    image: web-project:v1
    build: ./webapp
    ports:
      - 5173:5173
    networks:
      - web-net
    depends_on:
      - api

networks:
  web-net:
    driver: bridge

