version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile.api
    ports:
      - 5000:5000
    networks:
      - web-net
    # depends_on:
    #   - frontend

  frontend:
    build:
      context: .
      dockerfile: web/Dockerfile.web
    ports:
      - 5173:5173
    networks:
      - web-net

networks:
  web-net:
    driver: bridge

