apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-project
  template:
    metadata:
      labels:
        app: api-project
    spec:
      containers:
      - name: api-project
        image: api-project:v1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: backend
spec:
  type: NodePort
  selector:
    app: api-project
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30000 # Escoge un puerto disponible en tu cluster
